---
driver:
  name: lxd_cli

transport:
  name: sftp

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: test-kitchen
  ansible_verbose: true
#  ansible_verbose: false
  ansible_verbosity: 2
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
#  require_chef_omnibus: false
  require_ansible_omnibus: true
#  require_chef_for_busser: false
  enable_yum_epel: true
  ansible_connection: ssh

platforms:
  - name: ubuntu-18.04
## BUG/FIXME! v2.2: apt module not idempotent - task install w3af dependencies
  - name: ubuntu-16.04
  - name: ubuntu-14.04
    provisioner:
      ansible_version: 2.1.2.0
#  - name: ubuntu-12.04
  - name: centos-7
#  - name: centos-6
#  - name: alpine-3.4

suites:
  - name: default
    run_list:
    attributes:
