---

#- fail: msg="This role is only compatible with Ubuntu"
#  when: ansible_distribution != 'Ubuntu'

- name: Include version-specific variables for Ubuntu.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_distribution == 'Ubuntu'
- name: Include version-specific variables for RedHat
  include_vars: "RedHat-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == "RedHat"
- name: Include version-specific variables for Alpine
  include_vars: "Alpine.yml"
  when: ansible_os_family == "Alpine"

- debug: var=ansible_os_family
- debug: var=ansible_distribution_major_version
- debug: msg="yes"
  when: ansible_os_family != "RedHat" or ansible_distribution_major_version|int > 7

- include: w3af.yml

- include: w3af-scan.yml
  when: w3af_scan is defined and w3af_scan
